#personal.py
print("name: Harsha")
print("age: 21")
print("gender: male")
print("class: SSLC")
print("school: NRS ICSC School")
print("grade: 7.8")
print("college: SMV College")
print("percentage: 63")
print("university: Karnataka University")
print("degree: B.Sc")
print("course: Mathematics & Electronics")
print("CGPA: 7.5")
print("Internship: Axilex Pvt Ltd")
print("city: Hubballi")
print("country: India")
print("email: harsha........591@gmail.com")
print("phone: +91 123456789")